//
//--------------------------------------------------------------------------------
//          THIS FILE WAS AUTOMATICALLY GENERATED BY THE GENESIS2 ENGINE        
//  FOR MORE INFORMATION: OFER SHACHAM (CHIP GENESIS INC / STANFORD VLSI GROUP)
//    !! THIS VERSION OF GENESIS2 IS NOT FOR ANY COMMERCIAL USE !!
//     FOR COMMERCIAL LICENSE CONTACT SHACHAM@ALUMNI.STANFORD.EDU
//--------------------------------------------------------------------------------
//
//  
//	-----------------------------------------------
//	|            Genesis Release Info             |
//	|  $Change: 11904 $ --- $Date: 2013/08/03 $   |
//	-----------------------------------------------
//	
//
//  Source file: /afs/asu.edu/users/j/j/o/jjose3/combCore/combCore/rtl/alu.vp
//  Source template: alu
//
// --------------- Begin Pre-Generation Parameters Status Report ---------------
//
//	From 'generate' statement (priority=5):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Command Line input (priority=4):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From XML input (priority=3):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Config File input (priority=2):
//
// ---------------- End Pre-Generation Pramameters Status Report ----------------

// alu.vp
module alu (

		input  logic [3:0]  ctl,
		input  logic [31:0] a, b,
		input  logic [4:0]  shmt,
		output logic [31:0] out,
		output logic 	    gtz,
		output logic 	    zero);

	logic [31:0] sub_ab;
	logic [31:0] add_ab;
	logic 		oflow_add;
	logic 		oflow_sub;
	logic 		oflow;
	logic 		slt;
	logic [31:0]	tmp;

	assign zero = (0 == out);
	assign gtz  = a[31] ? 0 : (|a[31:0]); 

	assign sub_ab = a - b;
	assign add_ab = a + b;

	// overflow occurs (with 2s complement numbers) when
	// the operands have the same sign, but the sign of the result is
	// different.  The actual sign is the opposite of the result.
	// It is also dependent on whether addition or subtraction is performed.
	assign oflow_add = (a[31] == b[31] && add_ab[31] != a[31]) ? 1 : 0;
	assign oflow_sub = (a[31] == b[31] && sub_ab[31] != a[31]) ? 1 : 0;

	assign oflow = (ctl == 4'b0010) ? oflow_add : oflow_sub;

	// set if less than, 2s compliment 32-bit numbers
	assign slt = oflow_sub ? ~(a[31]) : a[31];

	always_comb begin
		unique case (ctl)
			4'd0:  		out = a & b;				/* and */
			4'd1:  		out = a | b;				/* or */
			4'd2:  		out = add_ab;				/* add */
			4'd6:  		out = sub_ab;				/* sub */
			4'd7:  		out = {{31{1'b0}}, slt};		/* slt */
			4'd12: 		out = ~(a | b);				/* nor */
			4'd13: 		out = a ^ b;				/* xor */
			4'd14: 		begin tmp = b >> shmt; out = ({32{b[31]}} << (32-shmt)) + tmp; end			/* sra */
			default: 	out = 0;
		endcase
	end

endmodule: alu
