//
//--------------------------------------------------------------------------------
//          THIS FILE WAS AUTOMATICALLY GENERATED BY THE GENESIS2 ENGINE        
//  FOR MORE INFORMATION: OFER SHACHAM (CHIP GENESIS INC / STANFORD VLSI GROUP)
//    !! THIS VERSION OF GENESIS2 IS NOT FOR ANY COMMERCIAL USE !!
//     FOR COMMERCIAL LICENSE CONTACT SHACHAM@ALUMNI.STANFORD.EDU
//--------------------------------------------------------------------------------
//
//  
//	-----------------------------------------------
//	|            Genesis Release Info             |
//	|  $Change: 11904 $ --- $Date: 2013/08/03 $   |
//	-----------------------------------------------
//	
//
//  Source file: /afs/asu.edu/users/j/j/o/jjose3/combCore/combCore/rtl/ctl.vp
//  Source template: ctl
//
// --------------- Begin Pre-Generation Parameters Status Report ---------------
//
//	From 'generate' statement (priority=5):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Command Line input (priority=4):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From XML input (priority=3):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Config File input (priority=2):
//
// ---------------- End Pre-Generation Pramameters Status Report ----------------

// ctl.vp
// bitWidth (_GENESIS2_DECLARATION_PRIORITY_) = 32
//
module ctl(
		input  logic [5:0] op,
		input  logic [5:0] func,
		output logic [5:0] mfunc,
		output logic       beq, bne, bgtz,
		output logic [1:0] aluop,
		output logic 	   aluimm,
		output logic       memrden, memwren, memtoreg,
		output logic       regdst, regwren, alusrc,
		output logic       jmpreg,
		output logic       jmp);

	always_comb begin
		aluop[1:0]	= 2'b10;
		aluimm		= 1'b0;
		alusrc		= 1'b0;
		beq      	= 1'b0;
		bne      	= 1'b0;
		bgtz      	= 1'b0;
		memrden		= 1'b0;
		memtoreg	= 1'b0;
		memwren 	= 1'b0;
		regdst		= 1'b1;
		regwren	        = 1'b1;
		jmp		= 1'b0;
		jmpreg		= 1'b0;
		mfunc		= 6'd0;

	       case (op)
			6'b100011: begin	/* lw */
				memrden  = 1'b1;
				regdst   = 1'b0;
				memtoreg = 1'b1;
				aluop    = 2'b00;
				alusrc   = 1'b1;
			end
			6'b001000: begin       /* addi */
				regdst   = 1'b0;
				alusrc   = 1'b1;
				aluimm   = 1'b1;
				mfunc     = 6'b100000;
			end
			6'b001100: begin       /* andi */
				regdst   = 1'b0;
				alusrc   = 1'b1;
				aluimm   = 1'b1;
				mfunc     = 6'b100100;
			end
			6'b001101: begin       /* ori */
				regdst   = 1'b0;
				alusrc   = 1'b1;
				aluimm   = 1'b1;
				mfunc     = 6'b100101;
			end
			6'b001010: begin       /* slti */
				regdst   = 1'b0;
				alusrc   = 1'b1;
				aluimm   = 1'b1;
				mfunc     = 6'b101010;
			end
			6'b001110: begin       /* xori */
				regdst   = 1'b0;
				alusrc   = 1'b1;
				aluimm   = 1'b1;
				mfunc     = 6'b100110;
			end
			6'b000100: begin	/* beq */
				aluop     = 2'b01;
				beq       = 1'b1;
				regwren  = 1'b0;
			end
			6'b000101: begin	/* bne */
				aluop     = 2'b01;
				bne       = 1'b1;
				regwren  = 1'b0;
			end
			6'b000111: begin	/* bgtz */
				aluop     = 2'b01;
				bgtz      = 1'b1;
				regwren  = 1'b0;
			end
			6'b101011: begin	/* sw */
				memwren  = 1'b1;
				aluop    = 2'b00;
				alusrc   = 1'b1;
				regwren = 1'b0;
			end
			6'b000000: begin	/* add, and, nor, or, slt, sub, xor, jr, sra */
				if(func == 6'h08) begin
					jmpreg = 1'b1;   /* jr */
					regdst		= 1'b0;
					regwren	= 1'b0;
				end else begin
					jmpreg = 1'b0;
				end
			end
			6'b000010: begin	/* j jump */
				jmp      = 1'b1;
			end
		endcase
	end
endmodule : ctl
